name: Checkout Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3 # actions:owner, checkout:repository
        with:
          path: source
      - run: ls -al
      - run: cat .github/workflows/checkout.yaml
