name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, Github Actions'
  pwd-ls:
    runs-on: ubuntu:latest
    steps:
      - name: Print working directory
        run: pwd
      - name: Change Directory
        run: cd ~
